function InicioScreen(){
	document.getElementById("Inicio").style.visibility="visible"; 
	document.getElementById("Indice").style.visibility="hidden";
	document.getElementById("Pantalla1").style.visibility="hidden";
	document.getElementById("Pantalla2").style.visibility="hidden";
	document.getElementById("Pantalla3").style.visibility="hidden";
	document.getElementById("Pantalla4").style.visibility="hidden";
	document.getElementById("BotonInicio").style.cursor="default";
	document.getElementById("BotonInfo").style.cursor="pointer";
	document.getElementById("Boton1").style.cursor="pointer";
	document.getElementById("Boton2").style.cursor="pointer";
	document.getElementById("Boton3").style.cursor="pointer";
	document.getElementById("Boton4").style.cursor="pointer";
}
function InfoScreen(){
	document.getElementById("Inicio").style.visibility="hidden";
	document.getElementById("Indice").style.visibility="visible";
	document.getElementById("Pantalla1").style.visibility="hidden";
	document.getElementById("Pantalla2").style.visibility="hidden";
	document.getElementById("Pantalla3").style.visibility="hidden";
	document.getElementById("Pantalla4").style.visibility="hidden";
	document.getElementById("BotonInicio").style.cursor="pointer";
	document.getElementById("BotonInfo").style.cursor="default";
	document.getElementById("Boton1").style.cursor="pointer";
	document.getElementById("Boton2").style.cursor="pointer";
	document.getElementById("Boton3").style.cursor="pointer";
	document.getElementById("Boton4").style.cursor="pointer";
}
function B1Screen(){
	document.getElementById("Inicio").style.visibility="hidden";
	document.getElementById("Indice").style.visibility="hidden";
	document.getElementById("Pantalla1").style.visibility="visible";
	document.getElementById("Pantalla2").style.visibility="hidden";
	document.getElementById("Pantalla3").style.visibility="hidden";
	document.getElementById("Pantalla4").style.visibility="hidden";
	document.getElementById("BotonInicio").style.cursor="pointer";
	document.getElementById("BotonInfo").style.cursor="pointer";
	document.getElementById("Boton1").style.cursor="default";
	document.getElementById("Boton2").style.cursor="pointer";
	document.getElementById("Boton3").style.cursor="pointer";
	document.getElementById("Boton4").style.cursor="pointer";
}
function B2Screen(){
	document.getElementById("Inicio").style.visibility="hidden";
	document.getElementById("Indice").style.visibility="hidden";
	document.getElementById("Pantalla1").style.visibility="hidden";
	document.getElementById("Pantalla2").style.visibility="visible";
	document.getElementById("Pantalla3").style.visibility="hidden";
	document.getElementById("Pantalla4").style.visibility="hidden";
	document.getElementById("BotonInicio").style.cursor="pointer";
	document.getElementById("BotonInfo").style.cursor="pointer";
	document.getElementById("Boton1").style.cursor="pointer";
	document.getElementById("Boton2").style.cursor="default";
	document.getElementById("Boton3").style.cursor="pointer";
	document.getElementById("Boton4").style.cursor="pointer";
}
function B3Screen(){
	document.getElementById("Inicio").style.visibility="hidden";
	document.getElementById("Indice").style.visibility="hidden";
	document.getElementById("Pantalla1").style.visibility="hidden";
	document.getElementById("Pantalla2").style.visibility="hidden";
	document.getElementById("Pantalla3").style.visibility="visible";
	document.getElementById("Pantalla4").style.visibility="hidden";
	document.getElementById("BotonInicio").style.cursor="pointer";
	document.getElementById("BotonInfo").style.cursor="pointer";
	document.getElementById("Boton1").style.cursor="pointer";
	document.getElementById("Boton2").style.cursor="pointer";
	document.getElementById("Boton3").style.cursor="default";
	document.getElementById("Boton4").style.cursor="pointer";
}
function B4Screen(){
	document.getElementById("Inicio").style.visibility="hidden";
	document.getElementById("Indice").style.visibility="hidden";
	document.getElementById("Pantalla1").style.visibility="hidden";
	document.getElementById("Pantalla2").style.visibility="hidden";
	document.getElementById("Pantalla3").style.visibility="hidden";
	document.getElementById("Pantalla4").style.visibility="visible";
	document.getElementById("BotonInicio").style.cursor="pointer";
	document.getElementById("BotonInfo").style.cursor="pointer";
	document.getElementById("Boton1").style.cursor="pointer";
	document.getElementById("Boton2").style.cursor="pointer";
	document.getElementById("Boton3").style.cursor="pointer";
	document.getElementById("Boton4").style.cursor="default";
}